name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
      - run: just publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
